# frozen_string_literal: true

module LabBridge
  # Ruby -> Rust generator: turns a Hartwell Labs Ruby plugin (a class with
  # `init`/`handle_event` hooks and a magic manifest header) into a Rust
  # source file implementing the `LabPlugin` trait expected by the
  # hartwell-labs plugin host (talus / aurora / externum bridges).
  #
  # The output is deterministic and human-readable: every Ruby construct is
  # either mapped onto the Rust subset or emitted as a `// TODO(labbridge)`
  # comment, so reviewers can audit generated code line by line.
  class Ruby2Rust
    HEADER = <<~RUST
      // Auto-generated by labbridge #{VERSION} — #{VENDOR}
      // Source: Ruby plugin (round-trip bridge, ruby2rust direction)
      // DO NOT EDIT BY HAND: regenerate with `labbridge r2rust <plugin.rb>`
      // Target contract: `LabPlugin` trait (hartwell-labs plugin host API v1)
    RUST

    RUST_MAP = {
      ".length" => ".len()", ".empty?" => ".is_empty()", ".to_s" => ".to_string()",
      ".to_i" => ".parse::<i64>().unwrap_or(0)", ".upcase" => ".to_uppercase()",
      ".downcase" => ".to_lowercase()", ".strip" => ".trim().to_string()"
    }.freeze

    CLASS_RE = /\A\s*class\s+([A-Z]\w*)/.freeze
    DEF_RE = /\A\s*def\s+(\w+)\s*(?:\(([^)]*)\))?\s*\z/.freeze
    END_RE = /\A\s*end\s*\z/.freeze
    PUTS_RE = /\A\s*puts\s+(.+?)\s*\z/.freeze
    WARN_RE = /\A\s*warn\s+(.+?)\s*\z/.freeze
    RET_RE = /\A\s*return\b\s*(.*?)\s*\z/.freeze
    RAISE_RE = /\A\s*raise\b\s*(.*?)\s*\z/.freeze
    MANIFEST_RE = /\A\s*#\s*hartwell-lab-plugin:/.freeze

    def initialize
      @out = []
      @indent = 0
    end

    def translate(source)
      @out.clear
      @indent = 0
      @manifest = Manifest.from_ruby(source)
      @struct = rust_struct(@manifest.name)
      @fn_open = nil
      @body_last = nil

      emit HEADER
      emit
      emit "pub struct #{@struct};"
      emit
      emit "impl LabPlugin for #{@struct} {"
      @indent += 1

      source.each_line(chomp: true) { |line| emit_line(line) }

      close_fn
      @indent -= 1
      emit "}"
      emit
      emit_footer
      @out.join("\n") + "\n"
    end
    alias call translate

    private

    def pad
      "    " * @indent
    end

    def emit(line = "")
      @out << (line.empty? ? "" : pad + line)
    end

    def todo(line)
      emit "// TODO(labbridge): unsupported Ruby construct: #{line.strip}"
    end

    def rust_struct(name)
      name.split(/[-_]/).map(&:capitalize).join
    end

    def open_fn(signature, kind)
      close_fn
      emit signature
      @indent += 1
      @fn_open = kind
      @body_last = nil
    end

    def close_fn
      return unless @fn_open

      if @fn_open == :plain
        # last bare expression (no semicolon) becomes the return value
        last = @out.rindex { |l| !l.empty? }
        @out[last] = @out[last].sub(/;\s*\z/, "") if last
      else
        emit "Ok(())" unless ok_ending?(@body_last)
      end
      @indent -= 1
      emit "}"
      emit
      @fn_open = nil
    end

    def ok_ending?(line)
      line.nil? || line.match?(/\A(?:return\s+)?Ok\(/) || line.match?(/\Areturn\b/)
    end

    # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    def emit_line(line)
      case line
      when /\A\s*\z/    then emit
      when MANIFEST_RE  then emit "// manifest: #{line.sub(/\A\s*#\s*/, '')}"
      when /\A\s*#/     then emit "// #{line.sub(/\A\s*#\s?/, '')}"
      when CLASS_RE     then nil # class wrapper is mapped onto impl LabPlugin
      when DEF_RE
        name, args = Regexp.last_match[1], Regexp.last_match[2].to_s
        case name
        when "init"
          open_fn("fn init(&self) -> LabResult {", :lab_result)
        when "handle_event"
          arg = args.split(",").map(&:strip).reject(&:empty?).first || "event"
          open_fn("fn handle_event(&self, #{arg}: &str) -> LabResult {", :lab_result)
        else
          params = args.split(",").map(&:strip).reject(&:empty?)
                       .map { |a| "#{a}: i64" }.join(", ")
          sig = params.empty? ? "fn #{name}(&self) -> i64 {" : "fn #{name}(&self, #{params}) -> i64 {"
          open_fn(sig, :plain)
        end
      when END_RE
        close_fn
      when PUTS_RE
        @body_last = line
        emit "println!(\"{}\", #{expr(Regexp.last_match[1])});"
      when WARN_RE
        @body_last = line
        emit "eprintln!(\"{}\", #{expr(Regexp.last_match[1])});"
      when RET_RE
        body = Regexp.last_match[1]
        @body_last = line
        if body.empty?
          emit "return Ok(());"
        elsif @fn_open == :lab_result
          emit "return Ok(#{expr(body)}.to_string());"
        else
          emit "return #{expr(body)};"
        end
      when RAISE_RE
        @body_last = line
        msg = Regexp.last_match[1].strip.gsub('"', "'")
        emit "return Err(LabError::Plugin(\"#{msg}\".into()));"
      when /\A\s*(.+?)\s*\z/
        @body_last = line
        code = expr(Regexp.last_match[1])
        if @fn_open == :lab_result
          emit "return Ok(#{code}.to_string());"
          @body_last = nil # ends with return Ok(...) — no extra Ok(()) needed
        else
          emit "#{code};"
        end
      end
    end
    # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

    def expr(code)
      RUST_MAP.each { |rb, rs| code = code.gsub(/\b#{Regexp.escape(rb)}/, rs) }
      code
    end

    def emit_footer
      emit "impl LabPluginRegistration for #{@struct} {"
      emit "    const NAME: &'static str = \"#{@manifest.name}\";"
      emit "    const TARGET: &'static str = \"#{@manifest.target}\";"
      emit "    const VERSION: &'static str = \"#{@manifest.version}\";"
      emit "}"
    end
  end
end
